SkiRental/SkiRental/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SkiRental.DAL;
using SkiRental.Models;

namespace SkiRental.Controllers
{
    public class ItemsController : Controller
    {
        private SkiRentalContext db = new SkiRentalContext();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Producer,Model,Price,Size,Description,isAvailable,PhotoUrl")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Producer,Model,Price,Size,Description,isAvailable,PhotoUrl")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SkiRental/SkiRental/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkiRental.Models;
using SkiRental.ViewModels;
using SkiRental.Services;

namespace SkiRental.Controllers
{
    public class OrdersController : Controller
    {
        private readonly OrderService _orderService = new OrderService();

        public ActionResult ToPay(string orderCode)
        {
            var payment = _orderService.GetPaymentByOrderCode(orderCode);

            return PartialView(payment);
        }

        public ActionResult Pay(int id)
        {
            string code = ViewBag.tmp;
            _orderService.Pay(id);

            // Niech wróci do detali
            return RedirectToAction("ListOrders");
        }

        [HttpGet]
        public ActionResult Index(int id)
        {
            ViewBag.CustomerId = id;

            return View(new OrderViewModel());
        }

        [HttpPost]
        public ActionResult Index(OrderViewModel orderModel)
        {
            var orderMapped = new Order()
            {   
                OrderCode = Guid.NewGuid().ToString(),
                CustomerId = orderModel.CustomerId,
                StartDate = orderModel.StartDate,
                EndDate = orderModel.EndDate,
                Opis = orderModel.Opis
            };

            _orderService.AddOrder(orderMapped);

            return RedirectToAction("AddItems", orderMapped);
        }

        public ActionResult AddItems(Order orderModel)
        {
            var listOfItem = _orderService.GetAllProduct();
            var orderInfo = _orderService.GetOrderByCode(orderModel.OrderCode);

            var orderModelWithItems = new OrderWithItemList()
            {
                CustomerId = orderModel.CustomerId,
                StartDate = orderModel.StartDate,
                EndDate = orderModel.EndDate,
                Opis = orderModel.Opis,
                Items = listOfItem,
                OrderCode = orderInfo.OrderCode
            };

            return View(orderModelWithItems);
        }

        [ChildActionOnly]
        public ActionResult GetCategory()
        {
            var categories = _orderService.GetListOfCategories();

            return PartialView(categories);
        }

        public ActionResult GetProducts(string category)
        {
            var products = _orderService.GetProducts(category);

            return PartialView(products);
        }

        public ActionResult CreateOrder(string pesel)
        {
            return View();
        }

        public ActionResult AddToOrder(int itemid, string ordercode)
        {

            var orderInfo = _orderService.GetOrderByCode(ordercode);

            var itemWithOrder = new OrderItem()
            {
                ItemId = itemid,
                OrderId = orderInfo.Id
            };

            _orderService.AddItemToOrder(itemWithOrder);
            _orderService.NotAvaliableItem(itemid);

            return RedirectToAction("AddItems", orderInfo);
        }

        //public ActionResult ListOrderItems()
        //{
        //    var items = _orderService.GetOrderItemsByOrderCode(ViewBag.orderCode);

        //    return View(items);
        //}

        public ActionResult ListOrders(string ordercode)
        {
            if (String.IsNullOrEmpty(ordercode))
            {
                var allOrders = _orderService.GetAllOrders();
                return View(allOrders);
            }

            return View(_orderService.GetOrderListByOrderCode(ordercode));
        }


        public ActionResult Details(int id)
        {
            var itemList = _orderService.GetItemsFromOrder(id);

            return View(itemList);
        }

        public ActionResult Delete(int id)
        {
            _orderService.RemoveOrder(id);
            
            return RedirectToAction("ListOrders");
        }

        public ActionResult Amount(int id)
        {
            var payment = _orderService.GetPaymentById(id);
            var order = _orderService.GetOrderByCode(payment.OrderCode);
            var suma = _orderService.Suma(order.Id);

            var amount = _orderService.ChangeAmount(payment.OrderCode, suma);

            ViewBag.Amount = amount;

            return PartialView();
            //return Content(suma.ToString());
        }

        //public ActionResult AddedItems(string ordercode)
        //{
        //    if(String.IsNullOrEmpty(ordercode))
        //    {
        //        return Content("String jest pusty");
        //    }

        //    var items = _orderService.GetAddedItems(ordercode);

        //    return Content("String nie jest pusty");

        //    //return PartialView();
        //}

        public ActionResult CreatePdf()
        {
            return View();
        }
    }
}

SkiRental/SkiRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SkiRental - Panel Administratora</title>

    <!-- Bootstrap Core CSS -->
    <link href="@Url.Content("~/Content/Dashboard/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />

    <!-- Custom CSS -->
    <link href="@Url.Content("~/Content/Dashboard/css/sb-admin.css")" rel="stylesheet" type="text/css" />

    <!-- Morris Charts CSS -->
    <link href="@Url.Content("~/Content/Dashboard/css/plugins/morris.css")" rel="stylesheet" type="text/css" />

    <!-- Custom Fonts -->
    <link href="@Url.Content("~/Content/Dashboard/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    @Styles.Render("~/Content/jqueryui")


</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Ski Rental</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Joanna Kowalska</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Joanna Kowalska</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>Joanna Kowalska</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Joanna Kowalska <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profil</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Wiadomości</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Ustawienia</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Wyloguj</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="@Url.Action("Index", "Home")"><i class="fa fa-fw fa-dashboard"></i> Pulpit</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#zamowienia"><i class="fa fa-fw fa-arrows-v"></i> Zamówienia <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="zamowienia" class="collapse">
                            <li>
                                <a href="@Url.Action("ListOrders", "Orders")">Wszystkie zamówienia</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Customers")">Nowe zamówienie</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Customers")"><i class="fa fa-fw fa-user"></i> Klienci</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Locations")"><i class="fa fa-fw fa-globe"></i> Lokalizacje</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Sprzęt <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="@Url.Action("Index", "ItemTypes")">Kategorie</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Items")">Sprzęt</a>
                            </li>
                        </ul>
                    </li>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#incident"><i class="fa fa-fw fa-arrows-v"></i> Incydenty <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="incident" class="collapse">
                            <li>
                                <a href="@Url.Action("Index", "ItemTypes")">Kategorie</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Items")">Sprzęt</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">

                        @RenderBody()

                    </div>
                </div>
                <!-- /.row -->



            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="@Url.Content("~/Content/Dashboard/js/jquery.js")"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="@Url.Content("~/Content/Dashboard/js/bootstrap.min.js")"></script>

    <!-- Morris Charts JavaScript -->
    <script src="@Url.Content("~/Content/Dashboard/js/plugins/morris/raphael.min.js")"></script>
    <script src="@Url.Content("~/Content/Dashboard/js/plugins/morris/morris.min.js")"></script>
    <script src="@Url.Content("~/Content/Dashboard/js/plugins/morris/morris-data.js")"></script>

    <!-- Kalendarz - jQuery UI -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")

    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)
</body>

</html>