SkiRental/SkiRental/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace SkiRental.Models
{
    public class Customer
    {
        public int Id { get; set; }
        [Display(Name = "Imię")]
        public string FirstName { get; set; }
        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }
        [Display(Name = "Numer telefonu")]
        public string Phone { get; set; }
        [Display(Name = "E-mail")]
        public string Email { get; set; }
        [Display(Name = "Kod pocztowy")]
        public string ZipCode { get; set; }
        [Display(Name = "Miasto")]
        public string City { get; set; }
        [Display(Name = "Adres")]
        public string Street { get; set; }
        [Display(Name = "VIP")]
        public bool IsVip { get; set; }
        [Display(Name = "Dokument tożsamości")]
        public string IdentityCard { get; set; }
        [Display(Name = "Seria dokumentu")]
        public string NumberOfIdentityCard { get; set; }
        [Display(Name = "PESEL")]
        public string Pesel { get; set; }
        [Display(Name = "Data dodania")]
        public DateTime CreateDate { get; set; }
        public virtual ICollection<Order> Oders { get; set; }
    }
}

SkiRental/SkiRental/ViewModels/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace SkiRental.ViewModels
{
    public class CustomerViewModel
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }
        [JsonProperty(PropertyName = "zipCode")]
        public string ZipCode { get; set; }
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }
        [JsonProperty(PropertyName = "street")]
        public string Street { get; set; }
        [JsonProperty(PropertyName = "isVip")]
        public bool IsVip { get; set; }
        [JsonProperty(PropertyName = "identityCard")]
        public string IdentityCard { get; set; }
        [JsonProperty(PropertyName = "numberOfIdentityCard")]
        public string NumberOfIdentityCard { get; set; }
        [JsonProperty(PropertyName = "pesel")]
        public string Pesel { get; set; }
        [JsonProperty(PropertyName = "createDate")]
        public DateTime CreateDate { get; set; }
    }
}

SkiRental/SkiRental/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SkiRental.DAL;
using SkiRental.Models;
using PagedList;
using PagedList.Mvc;

namespace SkiRental.Controllers
{
    public class CustomersController : Controller
    {
        private SkiRentalContext db = new SkiRentalContext();

        // GET: Customers
        public ActionResult Index(string pesel, int? page)
        {
            if(String.IsNullOrEmpty(pesel))
            {
                return View(db.Customers.ToList().ToPagedList(page ?? 1, 3));
            }

            return View(db.Customers.Where(c => c.Pesel == pesel).ToList().ToPagedList(page ?? 1, 3));
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Phone,Email,ZipCode,City,Street,IsVip,IdentityCard,NumberOfIdentityCard,Pesel,CreateDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Phone,Email,ZipCode,City,Street,IsVip,IdentityCard,NumberOfIdentityCard,Pesel,CreateDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SkiRental/SkiRental/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkiRental.Models;
using SkiRental.ViewModels;
using SkiRental.Services;

namespace SkiRental.Controllers
{
    public class OrdersController : Controller
    {
        private readonly OrderService _orderService = new OrderService();

        public ActionResult ToPay(string orderCode)
        {
            var payment = _orderService.GetPaymentByOrderCode(orderCode);

            return PartialView(payment);
        }

        public ActionResult Pay(int id)
        {
            string code = ViewBag.tmp;
            _orderService.Pay(id);

            // Niech wróci do detali
            return RedirectToAction("ListOrders");
        }

        [HttpGet]
        public ActionResult Index(int id)
        {
            ViewBag.CustomerId = id;

            return View(new OrderViewModel());
        }

        [HttpPost]
        public ActionResult Index(OrderViewModel orderModel)
        {
            var orderMapped = new Order()
            {   
                OrderCode = Guid.NewGuid().ToString(),
                CustomerId = orderModel.CustomerId,
                StartDate = orderModel.StartDate,
                EndDate = orderModel.EndDate,
                Opis = orderModel.Opis
            };

            _orderService.AddOrder(orderMapped);

            return RedirectToAction("AddItems", orderMapped);
        }

        public ActionResult AddItems(Order orderModel)
        {
            var listOfItem = _orderService.GetAllProduct();
            var orderInfo = _orderService.GetOrderByCode(orderModel.OrderCode);

            var orderModelWithItems = new OrderWithItemList()
            {
                CustomerId = orderModel.CustomerId,
                StartDate = orderModel.StartDate,
                EndDate = orderModel.EndDate,
                Opis = orderModel.Opis,
                Items = listOfItem,
                OrderCode = orderInfo.OrderCode
            };

            return View(orderModelWithItems);
        }

        [ChildActionOnly]
        public ActionResult GetCategory()
        {
            var categories = _orderService.GetListOfCategories();

            return PartialView(categories);
        }

        public ActionResult GetProducts(string category)
        {
            var products = _orderService.GetProducts(category);

            return PartialView(products);
        }

        public ActionResult CreateOrder(string pesel)
        {
            return View();
        }

        public ActionResult AddToOrder(int itemid, string ordercode)
        {

            var orderInfo = _orderService.GetOrderByCode(ordercode);

            var itemWithOrder = new OrderItem()
            {
                ItemId = itemid,
                OrderId = orderInfo.Id
            };

            _orderService.AddItemToOrder(itemWithOrder);
            _orderService.NotAvaliableItem(itemid);

            return RedirectToAction("AddItems", orderInfo);
        }

        //public ActionResult ListOrderItems()
        //{
        //    var items = _orderService.GetOrderItemsByOrderCode(ViewBag.orderCode);

        //    return View(items);
        //}

        public ActionResult ListOrders(string ordercode)
        {
            if (String.IsNullOrEmpty(ordercode))
            {
                var allOrders = _orderService.GetAllOrders();
                return View(allOrders);
            }

            return View(_orderService.GetOrderListByOrderCode(ordercode));
        }


        public ActionResult Details(int id)
        {
            var itemList = _orderService.GetItemsFromOrder(id);

            return View(itemList);
        }

        public ActionResult Delete(int id)
        {
            _orderService.RemoveOrder(id);
            
            return RedirectToAction("ListOrders");
        }

        public ActionResult Amount(int id)
        {
            var payment = _orderService.GetPaymentById(id);
            var order = _orderService.GetOrderByCode(payment.OrderCode);
            var suma = _orderService.Suma(order.Id);

            var amount = _orderService.ChangeAmount(payment.OrderCode, suma);

            ViewBag.Amount = amount;

            return PartialView();
            //return Content(suma.ToString());
        }

        //public ActionResult AddedItems(string ordercode)
        //{
        //    if(String.IsNullOrEmpty(ordercode))
        //    {
        //        return Content("String jest pusty");
        //    }

        //    var items = _orderService.GetAddedItems(ordercode);

        //    return Content("String nie jest pusty");

        //    //return PartialView();
        //}

        public ActionResult CreatePdf()
        {
            return View();
        }
    }
}

SkiRental/SkiRental/Views/Customers/Create.cshtml
@model SkiRental.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsVip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsVip)
                    @Html.ValidationMessageFor(model => model.IsVip, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdentityCard, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdentityCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdentityCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfIdentityCard, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfIdentityCard, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfIdentityCard, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pesel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pesel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pesel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SkiRental/SkiRental/Views/Customers/Delete.cshtml
@model SkiRental.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsVip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsVip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentityCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentityCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfIdentityCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfIdentityCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pesel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pesel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SkiRental/SkiRental/Views/Customers/Details.cshtml
@model SkiRental.Models.Customer

@{
    ViewBag.Title = "Szczegółowe informacje o kliencie";
}

<h2>Szegółowe informacje o kliencie</h2>

<div>
    <h4>Dane osobowe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsVip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsVip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdentityCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentityCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfIdentityCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfIdentityCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pesel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pesel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Usuń", "Delete", new { id = Model.Id }) |
    @Html.ActionLink("Powrót do listy", "Index")
</p>

SkiRental/SkiRental/Views/Customers/Index.cshtml
@*@model IEnumerable<SkiRental.Models.Customer>*@
@model IPagedList<SkiRental.Models.Customer>

@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Lista klientów";
}

<h2>Lista klientów</h2>

@using (Html.BeginForm())
{
    @*<p>
        Znajdź po numerze PESEL: @Html.TextBox("pesel")
        <input type="submit" value="Search" />
    </p>*@

    <div class="form-group">
        @*Znajdź po kodzie zamówienia: @Html.TextBox("ordercode", new htmlAttributes: new { @class = "form-control" })*@
        <input placeholder="PESEL" class="form-control col-md-2" style="display:inline-block;width:auto;margin-right:10px;" id="pesel" name="pesel" type="text" value="">
        <input style="display:inline-block" class="btn btn-default" type="submit" value="Wyszukaj" />

        <a style="float:right;" class="btn btn-default create" href="@Url.Action("Create", "Customers")">Dodaj klienta</a>
    </div>
}

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.FirstName)*@
            Imię
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.LastName)*@
            Nazwisko
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Phone)*@
            Telefon
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Email)*@
            E-mail
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Pesel)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr @if (item.IsVip) { @Html.Raw("style=\"background: #ffffd4;\"") }>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pesel)
        </td>
        <td style="text-align:right;">
            @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Szczegóły", "Details", "Details", null, new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |*@
            <a href="@Url.Action("Details", "Customers", new { id=item.Id})">Szczegóły</a> |
            <a href="@Url.Action("Index", "Orders", new { id=item.Id})">Złóż zamówienie</a>
            @*@Html.ActionLink("Index", "Orders", new { id = item.Id })*@
        </td>
    </tr>
}
</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))