SkiRental/SkiRental/Models/Incident.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace SkiRental.Models
{
    public class Incident
    {
        public int Id { get; set; }
        [Display(Name = "Opis")]
        public string Description { get; set; }
        [Display(Name = "Koszt")]
        public decimal Cost { get; set; }
        public int ItemId { get; set; }
        public int IncidentTypeId { get; set; }
        public virtual IncidentType IncidentType { get; set; }
    }
}

SkiRental/SkiRental/Models/IncidentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace SkiRental.Models
{
    public class IncidentType
    {
        public int Id { get; set; }
        [Display(Name = "Incydent")]
        public string Name { get; set; }
        public virtual ICollection<Incident> Incident { get; set; }
    }
}

SkiRental/SkiRental/ViewModels/IncidentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SkiRental.ViewModels
{
    public class IncidentViewModel
    {
        //public int Id { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public int ItemId { get; set; }
        public int IncidentTypeId { get; set; }
    }
}

SkiRental/SkiRental/Controllers/IncidentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SkiRental.Models;
using SkiRental.Services;
using SkiRental.ViewModels;

namespace SkiRental.Controllers
{
    public class IncidentController : Controller
    {
        private readonly IncidentService _incidentService = new IncidentService();

        // GET: Incident
        public ActionResult Index()
        {
            var incidents = _incidentService.GetAllIncidents();

            return View(incidents);
        }

        public ActionResult ListItems()
        {
            var items = _incidentService.GetItems();

            return PartialView(items);
        }

        public ActionResult AddIncident()
        {
            var selectItems = _incidentService.GetSelectItems();
            ViewBag.SelectItems = selectItems;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddIncident(IncidentViewModel incidentViewModel)
        {
            _incidentService.AddIncident(incidentViewModel);
            var incidents = _incidentService.GetAllIncidents();

            return RedirectToAction("Index", incidents);
        }
    }
}

SkiRental/SkiRental/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SkiRental.DAL;
using SkiRental.Models;

namespace SkiRental.Controllers
{
    public class ItemsController : Controller
    {
        private SkiRentalContext db = new SkiRentalContext();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Producer,Model,Price,Size,Description,isAvailable,PhotoUrl")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Producer,Model,Price,Size,Description,isAvailable,PhotoUrl")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SkiRental/SkiRental/Views/Incident/AddIncident.cshtml
@model SkiRental.Models.Incident

@{
    ViewBag.Title = "AddIncident";
}

<h2>Dodaj incydent</h2>

@using (Html.BeginForm(@Html.BeginForm("AddIncident", "Incident")))
{
    @Html.AntiForgeryToken()

    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })

    @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })

    @Html.LabelFor(model => model.ItemId, htmlAttributes: new { @class = "control-label col-md-2" })
    @Html.EditorFor(model => model.ItemId, new { htmlAttributes = new { @class = "form-control itemId" } })

    @*@Html.LabelFor(model => model.IncidentTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(model => model.IncidentTypeId, new { htmlAttributes = new { @class = "form-control" } })*@
    <label>Typ incydentu</label>
    @Html.DropDownList("SelectItems", "Wybierz rodzaj")

    <label>Wybrany rodzaj:</label>
    <input class="form-control text-box single-line" id="IncidentTypeId" name="IncidentTypeId">

    <input type="submit" value="Utwórz" class="btn btn-default" />
}

<h3>Wybierz przedmiot</h3>

@Html.Action("ListItems", "Incident")

@section scripts {
    <script>
        $(document).ready(function () {
            $("tr").click(function () {
                var id = $(this).find(">:first-child").text();

                $(".itemId").val(id);
            });

            $("select").on("change", function () {
                var text = $("select option:selected").val();
                $("#IncidentTypeId").val(text);
            });
        });
    </script>
}

SkiRental/SkiRental/Views/Incident/Index.cshtml
@model List<SkiRental.Models.Incident>

@{
    ViewBag.Title = "Index";
}

<h2>Lista incydentów</h2>
<hr />

@if (Model.Count == 0)
{
    <div class="alert alert-warning">Brak incydentów</div>
}

@if (Model.Count != 0)
{
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Incydent</th>
            <th>Opis</th>
            <th>Koszt</th>
            <th></th>
        </tr>
        @foreach (var incident in Model)
        {
            <tr>
                <td>@incident.Id</td>
                <td>@incident.IncidentType.Name</td>
                <td>@incident.Description</td>
                <td>@incident.Cost</td>
                <td>@Html.ActionLink("Produkt", "Details", "Items", new { id = incident.ItemId }, null)</td>
            </tr>
        }
    </table>
}

SkiRental/SkiRental/Views/Incident/ListItems.cshtml
@model List<SkiRental.Models.Item>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Model</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="@item.Id">@item.Id</td>
            <td>@item.Model</td>
        </tr>
    }
</table>